# Exports the reference CV (.docx) to public/pdf/cv.pdf via Microsoft Word.
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File scripts\export-cv-pdf.ps1
#
# Why this script exists, and why the PDF is not generated by the build:
# there is no CLI converter on this machine (no soffice / libreoffice / pandoc),
# so Word is the only option, and Word needs a bit of coaxing (see below).
# See docs/cv-source.md for the full CV refresh procedure.
#
# NOTE: keep this file pure ASCII. Windows PowerShell 5.1 reads a .ps1 saved as
# UTF-8 without a BOM using the system ANSI codepage, so a UTF-8 em dash in a
# comment decodes to a sequence containing a double quote and unbalances every
# string literal after it, producing baffling "missing terminator" errors.

$ErrorActionPreference = 'Stop'

$source = Join-Path $HOME 'OneDrive - Adapt IT\Documents\personal\Siphephelo_Sibanyoni CV 2026.docx'
$target = Join-Path $PSScriptRoot '..\public\pdf\cv.pdf'
$wdExportFormatPDF = 17

if (-not (Test-Path -LiteralPath $source)) {
    Write-Error "Reference CV not found at: $source"
    exit 1
}

$targetFull = [System.IO.Path]::GetFullPath($target)
$targetDir = Split-Path -Parent $targetFull
if (-not (Test-Path -LiteralPath $targetDir)) {
    New-Item -ItemType Directory -Force -Path $targetDir | Out-Null
}

Write-Host "Source : $source"
Write-Host "Target : $targetFull"

# ExportAsFixedFormat initialises the default printer's driver to obtain page
# metrics. If the default printer is a NETWORK printer that is currently
# unreachable (for example \\10.245.101.248\Ysoft when off the office network),
# Word blocks on it forever: the document opens, then the process goes
# Responding = False with no dialog and no output at all. So switch to the local
# "Microsoft Print to PDF" for the duration, and restore the original after.
$originalPrinter = $null
$localPrinter = 'Microsoft Print to PDF'
try {
    $current = Get-CimInstance Win32_Printer | Where-Object { $_.Default }
    $local = Get-CimInstance Win32_Printer | Where-Object { $_.Name -eq $localPrinter }
    if ($current -and $local -and $current.Name -ne $localPrinter) {
        $originalPrinter = $current.Name
        Write-Host "Default printer is '$originalPrinter'; switching to '$localPrinter'."
        $local | Invoke-CimMethod -MethodName SetDefaultPrinter | Out-Null
    } elseif (-not $local) {
        Write-Warning "'$localPrinter' not available; export may hang on an unreachable printer."
    }
} catch {
    Write-Warning "Could not inspect or change the default printer: $($_.Exception.Message)"
}

Write-Host 'Starting Word...'

$word = $null
$doc = $null
try {
    $word = New-Object -ComObject Word.Application
    # Visible on purpose. With Visible = $false any dialog Word raises (an
    # activation prompt, a OneDrive sign-in, a file-recovery pane) is invisible
    # and cannot be dismissed, so the script just hangs with no output.
    $word.Visible = $true
    $word.DisplayAlerts = 0

    $doc = $word.Documents.Open($source, $false, $true)
    $doc.ExportAsFixedFormat($targetFull, $wdExportFormatPDF)

    Write-Host 'Export complete.' -ForegroundColor Green
}
finally {
    if ($doc)  { try { $doc.Close($false) } catch {} }
    if ($word) { try { $word.Quit() } catch {} }

    # Always restore, including on failure: silently leaving the default printer
    # changed would be a nasty side effect of running an export script.
    if ($originalPrinter) {
        try {
            $orig = Get-CimInstance Win32_Printer | Where-Object { $_.Name -eq $originalPrinter }
            $orig | Invoke-CimMethod -MethodName SetDefaultPrinter | Out-Null
            Write-Host "Restored default printer to '$originalPrinter'."
        } catch {
            Write-Warning "FAILED to restore default printer to '$originalPrinter'. Set it back manually."
        }
    }
}

if (Test-Path -LiteralPath $targetFull) {
    $size = (Get-Item -LiteralPath $targetFull).Length
    Write-Host ("PDF written: {0:N0} bytes" -f $size) -ForegroundColor Green
    if ($size -lt 20000) {
        Write-Warning 'Suspiciously small for a multi-page CV. Open it and check before committing.'
    }
} else {
    Write-Error 'No PDF was produced.'
    exit 1
}
